spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cryptovault
    username: cryptovault
    password: cryptovault123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.jminango.cryptovault: DEBUG
    org.springframework.security: DEBUG